"""Build the GitHub Pages demo site from demo/evtx.

    python scripts/build_site.py --out site --base-url https://<user>.github.io/crabwalk

Writes index.html (landing page), report.html, attack-paths.html,
findings.json and navigator-layer.json. The base URL lets the landing page
open the layer directly in the ATT&CK Navigator (#layerURL=...).
"""

from __future__ import annotations

import argparse
import html
import json
import sys
from collections import Counter
from pathlib import Path
from urllib.parse import quote

from crabwalk import __version__
from crabwalk.graph import build_graph, render_page
from crabwalk.navigator import build_layer
from crabwalk.parser import ParseStats, iter_events
from crabwalk.report import render_report
from crabwalk.rules import hunt
from crabwalk.style import SEVERITY_COLOR, SEVERITY_ORDER, page_head

ROOT = Path(__file__).resolve().parent.parent
REPO = "https://github.com/IlkerUnver00/crabwalk"
NAVIGATOR = "https://mitre-attack.github.io/attack-navigator/"


def build(out: Path, base_url: str | None) -> dict[str, int]:
    out.mkdir(parents=True, exist_ok=True)
    stats = ParseStats()
    ctx, findings = hunt(iter_events([ROOT / "demo" / "evtx"], stats=stats))
    graph = build_graph(ctx, findings)
    layer = build_layer(findings, name="crabwalk demo")

    (out / "report.html").write_text(
        render_report(ctx, findings, stats=stats, title="crabwalk — demo report"), encoding="utf-8")
    (out / "attack-paths.html").write_text(
        render_page(graph, title="crabwalk — demo attack paths"), encoding="utf-8")
    (out / "navigator-layer.json").write_text(json.dumps(layer, indent=2), encoding="utf-8")
    (out / "findings.json").write_text(
        json.dumps({"findings": [f.to_dict() for f in findings]}, indent=2), encoding="utf-8")

    by_severity = Counter(f.severity for f in findings)
    (out / "index.html").write_text(
        _landing(stats, len(findings), by_severity, len(graph.edges), len(layer["techniques"]), base_url),
        encoding="utf-8")
    (out / ".nojekyll").write_text("", encoding="utf-8")
    return {"findings": len(findings), "edges": len(graph.edges), "techniques": len(layer["techniques"])}


def _landing(stats: ParseStats, total: int, by_severity: Counter, edges: int, techniques: int,
             base_url: str | None) -> str:
    esc = html.escape
    severities = "".join(
        f'<span class="lg"><span class="dot" style="background:{SEVERITY_COLOR[s]}"></span>'
        f"{s.capitalize()} <b>{by_severity[s]}</b></span>"
        for s in SEVERITY_ORDER if by_severity[s]
    )
    if base_url:
        layer_url = base_url.rstrip("/") + "/navigator-layer.json"
        navigator = (f'<a class="card link" href="{esc(NAVIGATOR + "#layerURL=" + quote(layer_url, safe=""))}">'
                     "<h2>ATT&amp;CK Navigator</h2><p class=\"muted\">The techniques behind these findings as a "
                     "heatmap on the ATT&amp;CK matrix, opened straight from this site.</p></a>")
    else:  # local build: no public URL the Navigator could fetch
        navigator = ('<a class="card link" href="navigator-layer.json"><h2>ATT&amp;CK Navigator layer</h2>'
                     '<p class="muted">Download and open it in the ATT&amp;CK Navigator.</p></a>')
    return f"""{page_head("crabwalk — live demo")}
<style>
.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:14px;margin:16px 0}}
.link{{display:block;color:inherit;text-decoration:none}}
.link:hover{{border-color:#2a78d6;text-decoration:none}}
.link h2{{color:#2a78d6;margin-bottom:6px}}
.link p{{margin:0}}
</style>
<header class="hero"><div class="crab">\U0001f980</div><div>
<h1>crabwalk — live demo</h1>
<p class="muted">Windows EVTX lateral-movement hunter: stateful cross-host correlation, an attack-path graph,
and MITRE ATT&amp;CK mapping. Generated by crabwalk {esc(__version__)} from the bundled demo logs.</p>
</div></header>
<section class="tiles">
<div class="tile"><div class="tile-v">{stats.files}</div><div class="tile-k">EVTX files</div></div>
<div class="tile"><div class="tile-v">{stats.records}</div><div class="tile-k">Records</div></div>
<div class="tile"><div class="tile-v">{total}</div><div class="tile-k">Findings</div></div>
<div class="tile"><div class="tile-v">{edges}</div><div class="tile-k">Attack-path edges</div></div>
<div class="tile"><div class="tile-v">{techniques}</div><div class="tile-k">ATT&amp;CK techniques</div></div>
</section>
<section class="card"><div class="legend" style="margin-top:0">{severities}</div></section>
<div class="grid">
<a class="card link" href="report.html"><h2>Report</h2><p class="muted">The self-contained HTML report:
attack paths, severity, ATT&amp;CK coverage, timeline and every finding.</p></a>
<a class="card link" href="attack-paths.html"><h2>Attack paths</h2><p class="muted">The interactive graph:
hover or click a host to follow where the attacker came from and went next.</p></a>
{navigator}
<a class="card link" href="findings.json"><h2>findings.json</h2><p class="muted">The raw findings, as
<code>crabwalk hunt --out</code> writes them.</p></a>
</div>
<section class="card">
<h2>About this data</h2>
<p>Nine unmodified recordings from the public
<a href="https://github.com/sbousseaden/EVTX-ATTACK-SAMPLES">EVTX-ATTACK-SAMPLES</a> corpus (GPL-3.0),
bundled in the repository's <a href="{REPO}/tree/main/demo">demo folder</a>. They are separate lab captures,
not one intrusion — <a href="{REPO}/blob/main/demo/README.md">what each file shows</a>.
Rebuilt on every push to <a href="{REPO}">the repository</a>; run it yourself with
<code>crabwalk hunt demo/evtx --report report.html</code>.</p>
</section>"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=Path("site"))
    parser.add_argument("--base-url", help="public URL of the site, for the Navigator link")
    args = parser.parse_args(argv)
    summary = build(args.out, args.base_url)
    print(f"site -> {args.out}: {summary['findings']} findings, {summary['edges']} edges, "
          f"{summary['techniques']} techniques")
    return 0


if __name__ == "__main__":
    sys.exit(main())
